### ISSUE TITLE
ytview_2  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/ 

### ISSUE THREAD

**Issue by Footsiefat** [soumyadityac/youtube-viewer#1]
reating network "youtube-viewer-master_default" with the default driver
Creating youtube-viewer-master_ytview_1 ... done
Creating youtube-viewer-master_ytview_2 ... done
Creating youtube-viewer-master_ytview_3 ... done
Creating youtube-viewer-master_ytview_4 ... done
Creating youtube-viewer-master_ytview_5 ... done
Attaching to youtube-viewer-master_ytview_1, youtube-viewer-master_ytview_2, youtube-viewer-master_ytview_5, youtube-viewer-master_ytview_4, youtube-viewer-master_ytview_3
ytview_2  | [INFO] [11:45:48 PM] Preparing to generate 96 views. Target URL(s): https://www.youtube.com/watch?v=dQw4w9WgXcQ Duration: 50 seconds                                                                                                
ytview_2  | [INFO] [11:45:48 PM] App running in production. Will use rotating proxy via TOR.
ytview_2  | [INFO] [11:45:48 PM] -------- Writing Tor Config -------- 
ytview_2  | 
ytview_2  | [SUCCESS] [11:45:48 PM] PORT 9057 written in tor config
ytview_2  | [SUCCESS] [11:45:48 PM] PORT 9056 written in tor config
ytview_2  | [SUCCESS] [11:45:48 PM] PORT 9055 written in tor config
ytview_2  | [SUCCESS] [11:45:48 PM] PORT 9054 written in tor config
ytview_2  | [SUCCESS] [11:45:48 PM] PORT 9053 written in tor config
ytview_2  | [SUCCESS] [11:45:48 PM] PORT 9052 written in tor config
ytview_2  | [INFO] [11:45:48 PM] Starting TOR.
ytview_2  | [INFO] [11:45:48 PM] Failed to stop TOR. Usually this is a no op but ensure the subsequent attempts are using different IPs.                                                                                                        
ytview_2  | [SUCCESS] [11:45:48 PM] Started TOR successfully
ytview_1  | [INFO] [11:45:48 PM] Preparing to generate 96 views. Target URL(s): https://www.youtube.com/watch?v=dQw4w9WgXcQ Duration: 50 seconds                                                                                                
ytview_1  | [INFO] [11:45:48 PM] App running in production. Will use rotating proxy via TOR.
ytview_1  | [INFO] [11:45:48 PM] -------- Writing Tor Config -------- 
ytview_1  | 
ytview_1  | [SUCCESS] [11:45:48 PM] PORT 9056 written in tor config
ytview_1  | [SUCCESS] [11:45:48 PM] PORT 9055 written in tor config
ytview_1  | [SUCCESS] [11:45:48 PM] PORT 9054 written in tor config
ytview_1  | [SUCCESS] [11:45:48 PM] PORT 9053 written in tor config
ytview_1  | [SUCCESS] [11:45:48 PM] PORT 9052 written in tor config
ytview_1  | [SUCCESS] [11:45:48 PM] PORT 9057 written in tor config
ytview_1  | [INFO] [11:45:48 PM] Starting TOR.
ytview_1  | [INFO] [11:45:48 PM] Failed to stop TOR. Usually this is a no op but ensure the subsequent attempts are using different IPs.                                                                                                        
ytview_1  | [SUCCESS] [11:45:48 PM] Started TOR successfully
ytview_4  | [INFO] [11:45:48 PM] Preparing to generate 96 views. Target URL(s): https://www.youtube.com/watch?v=dQw4w9WgXcQ Duration: 50 seconds                                                                                                
ytview_4  | [INFO] [11:45:48 PM] App running in production. Will use rotating proxy via TOR.
ytview_4  | [INFO] [11:45:48 PM] -------- Writing Tor Config -------- 
ytview_4  | 
ytview_4  | [SUCCESS] [11:45:48 PM] PORT 9057 written in tor config
ytview_4  | [SUCCESS] [11:45:48 PM] PORT 9056 written in tor config
ytview_4  | [SUCCESS] [11:45:48 PM] PORT 9055 written in tor config
ytview_4  | [SUCCESS] [11:45:48 PM] PORT 9053 written in tor config
ytview_4  | [SUCCESS] [11:45:48 PM] PORT 9052 written in tor config
ytview_4  | [SUCCESS] [11:45:48 PM] PORT 9054 written in tor config
ytview_4  | [INFO] [11:45:48 PM] Starting TOR.
ytview_4  | [INFO] [11:45:48 PM] Failed to stop TOR. Usually this is a no op but ensure the subsequent attempts are using different IPs.                                                                                                        
ytview_4  | [SUCCESS] [11:45:48 PM] Started TOR successfully
ytview_5  | [INFO] [11:45:48 PM] Preparing to generate 96 views. Target URL(s): https://www.youtube.com/watch?v=dQw4w9WgXcQ Duration: 50 seconds                                                                                                
ytview_5  | [INFO] [11:45:48 PM] App running in production. Will use rotating proxy via TOR.
ytview_5  | [INFO] [11:45:48 PM] -------- Writing Tor Config -------- 
ytview_5  | 
ytview_5  | [SUCCESS] [11:45:48 PM] PORT 9057 written in tor config
ytview_5  | [SUCCESS] [11:45:48 PM] PORT 9056 written in tor config
ytview_5  | [SUCCESS] [11:45:48 PM] PORT 9055 written in tor config
ytview_5  | [SUCCESS] [11:45:48 PM] PORT 9054 written in tor config
ytview_5  | [SUCCESS] [11:45:48 PM] PORT 9053 written in tor config
ytview_5  | [SUCCESS] [11:45:48 PM] PORT 9052 written in tor config
ytview_5  | [INFO] [11:45:48 PM] Starting TOR.
ytview_5  | [INFO] [11:45:48 PM] Failed to stop TOR. Usually this is a no op but ensure the subsequent attempts are using different IPs.                                                                                                        
ytview_5  | [SUCCESS] [11:45:48 PM] Started TOR successfully
ytview_3  | [INFO] [11:45:49 PM] Preparing to generate 96 views. Target URL(s): https://www.youtube.com/watch?v=dQw4w9WgXcQ Duration: 50 seconds                                                                                                
ytview_3  | [INFO] [11:45:49 PM] App running in production. Will use rotating proxy via TOR.
ytview_3  | [INFO] [11:45:49 PM] -------- Writing Tor Config -------- 
ytview_3  | 
ytview_3  | [SUCCESS] [11:45:49 PM] PORT 9056 written in tor config
ytview_3  | [SUCCESS] [11:45:49 PM] PORT 9055 written in tor config
ytview_3  | [SUCCESS] [11:45:49 PM] PORT 9054 written in tor config
ytview_3  | [SUCCESS] [11:45:49 PM] PORT 9053 written in tor config
ytview_3  | [SUCCESS] [11:45:49 PM] PORT 9052 written in tor config
ytview_3  | [SUCCESS] [11:45:49 PM] PORT 9057 written in tor config
ytview_3  | [INFO] [11:45:49 PM] Starting TOR.
ytview_3  | [INFO] [11:45:49 PM] Failed to stop TOR. Usually this is a no op but ensure the subsequent attempts are using different IPs.                                                                                                        
ytview_3  | [SUCCESS] [11:45:50 PM] Started TOR successfully
ytview_1  | [ERROR] [11:46:23 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_2  | [ERROR] [11:46:23 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_1  | [ERROR] [11:46:23 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_5  | [ERROR] [11:46:23 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_4  | [ERROR] [11:46:23 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_2  | [ERROR] [11:46:23 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_1  | [ERROR] [11:46:23 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_5  | [ERROR] [11:46:23 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_1  | [ERROR] [11:46:23 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_4  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_1  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_1  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_5  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_1  | [INFO] [11:46:24 PM] View 1 - fulfilled
ytview_1  | [INFO] [11:46:24 PM] Success - 1     Failed - 0      Total - 1
ytview_1  | [INFO] [11:46:24 PM] View 2 - fulfilled
ytview_1  | [INFO] [11:46:24 PM] Success - 2     Failed - 0      Total - 2
ytview_1  | [INFO] [11:46:24 PM] View 3 - fulfilled
ytview_1  | [INFO] [11:46:24 PM] Success - 3     Failed - 0      Total - 3
ytview_1  | [INFO] [11:46:24 PM] View 4 - fulfilled
ytview_1  | [INFO] [11:46:24 PM] Success - 4     Failed - 0      Total - 4
ytview_1  | [INFO] [11:46:24 PM] View 5 - fulfilled
ytview_1  | [INFO] [11:46:24 PM] Success - 5     Failed - 0      Total - 5
ytview_1  | [INFO] [11:46:24 PM] View 6 - fulfilled
ytview_1  | [INFO] [11:46:24 PM] Success - 6     Failed - 0      Total - 6
ytview_1  | [INFO] [11:46:24 PM] Starting TOR.
ytview_2  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_2  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_5  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_2  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_4  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_2  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_4  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_5  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_5  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_4  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_4  | [ERROR] [11:46:24 PM] Entire view action in a batch failed. Error: Error: net::ERR_TIMED_OUT at https://api.ipify.org/                                                                                                              
ytview_5  | [INFO] [11:46:24 PM] View 1 - fulfilled
ytview_5  | [INFO] [11:46:24 PM] Success - 1     Failed - 0      Total - 1
ytview_5  | [INFO] [11:46:24 PM] View 2 - fulfilled
ytview_5  | [INFO] [11:46:24 PM] Success - 2     Failed - 0      Total - 2
ytview_5  | [INFO] [11:46:24 PM] View 3 - fulfilled
ytview_5  | [INFO] [11:46:24 PM] Success - 3     Failed - 0      Total - 3
ytview_5  | [INFO] [11:46:24 PM] View 4 - fulfilled
ytview_5  | [INFO] [11:46:24 PM] Success - 4     Failed - 0      Total - 4
ytview_5  | [INFO] [11:46:24 PM] View 5 - fulfilled
ytview_5  | [INFO] [11:46:24 PM] Success - 5     Failed - 0      Total - 5
ytview_5  | [INFO] [11:46:24 PM] View 6 - fulfilled
ytview_5  | [INFO] [11:46:24 PM] Success - 6     Failed - 0      Total - 6
ytview_2  | [INFO] [11:46:24 PM] View 1 - fulfilled
ytview_2  | [INFO] [11:46:24 PM] Success - 1     Failed - 0      Total - 1
ytview_2  | [INFO] [11:46:24 PM] View 2 - fulfilled
ytview_5  | [INFO] [11:46:24 PM] Starting TOR.
ytview_4  | [INFO] [11:46:24 PM] View 1 - fulfilled
ytview_4  | [INFO] [11:46:24 PM] Success - 1     Failed - 0      Total - 1
ytview_2  | [INFO] [11:46:24 PM] Success - 2     Failed - 0      Total - 2
ytview_2  | [INFO] [11:46:24 PM] View 3 - fulfilled
ytview_2  | [INFO] [11:46:24 PM] Success - 3     Failed - 0      Total - 3
ytview_4  | [INFO] [11:46:24 PM] View 2 - fulfilled
ytview_4  | [INFO] [11:46:24 PM] Success - 2     Failed - 0      Total - 2
ytview_2  | [INFO] [11:46:24 PM] View 4 - fulfilled
ytview_2  | [INFO] [11:46:24 PM] Success - 4     Failed - 0      Total - 4
ytview_2  | [INFO] [11:46:24 PM] View 5 - fulfilled
ytview_2  | [INFO] [11:46:24 PM] Success - 5     Failed - 0      Total - 5
ytview_4  | [INFO] [11:46:24 PM] View 3 - fulfilled
ytview_4  | [INFO] [11:46:24 PM] Success - 3     Failed - 0      Total - 3
ytview_4  | [INFO] [11:46:24 PM] View 4 - fulfilled
ytview_2  | [INFO] [11:46:24 PM] View 6 - fulfilled
ytview_2  | [INFO] [11:46:24 PM] Success - 6     Failed - 0      Total - 6
ytview_2  | [INFO] [11:46:24 PM] Starting TOR.
ytview_4  | [INFO] [11:46:24 PM] Success - 4     Failed - 0      Total - 4
ytview_4  | [INFO] [11:46:24 PM] View 5 - fulfilled
ytview_4  | [INFO] [11:46:24 PM] Success - 5     Failed - 0      Total - 5
ytview_4  | [INFO] [11:46:24 PM] View 6 - fulfilled
ytview_4  | [INFO] [11:46:24 PM] Success - 6     Failed - 0      Total - 6
ytview_4  | [INFO] [11:46:24 PM] Starting TOR.
ytview_1  | [SUCCESS] [11:46:24 PM] Started TOR successfully
ytview_4  | [SUCCESS] [11:46:24 PM] Started TOR successfully
ytview_5  | [SUCCESS] [11:46:24 PM] Started TOR successfully
ytview_2  | [SUCCESS] [11:46:24 PM] Started TOR successfully
ytview_3  | [ERROR] [11:46:48 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 51.68.201.118 was probably blocked.
ytview_3  | [ERROR] [11:46:49 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.193 was probably blocked.
ytview_4  | [ERROR] [11:47:04 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.152 was probably blocked.
ytview_4  | [ERROR] [11:47:10 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 199.249.230.75 was probably blocked.
ytview_4  | [ERROR] [11:47:11 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.201 was probably blocked.
ytview_5  | [ERROR] [11:47:12 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.214 was probably blocked.
ytview_5  | [ERROR] [11:47:13 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.130 was probably blocked.
ytview_1  | [ERROR] [11:47:13 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.135 was probably blocked.        
ytview_5  | [ERROR] [11:47:13 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 79.137.79.167 was probably blocked.                     
ytview_3  | [ERROR] [11:47:17 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 109.70.100.34 was probably blocked.                     
ytview_5  | [ERROR] [11:47:17 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.136 was probably blocked.                             
ytview_1  | [ERROR] [11:47:17 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.14 was probably blocked.                                            
ytview_2  | [ERROR] [11:47:20 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.10 was probably blocked.                                            
ytview_2  | [ERROR] [11:47:20 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.141 was probably blocked.                                                 
ytview_2  | [ERROR] [11:47:20 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 51.89.226.199 was probably blocked.                                                   
ytview_2  | [ERROR] [11:47:20 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.101.18 was probably blocked.
ytview_1  | [ERROR] [11:47:21 PM] An attempt to view https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 51.89.114.178 was probably blocked.
ytview_5  | [SUCCESS] [11:48:10 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.102.6 for 47.45049369376864 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)                                                                                                                                                                      
ytview_3  | [SUCCESS] [11:48:19 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 109.70.100.23 for 55.213079007762886 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)                                                                                                                                                                     
ytview_3  | [SUCCESS] [11:48:22 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.102.8 for 56.25011003268105 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)                                                                                                                                                                      
ytview_3  | [SUCCESS] [11:48:23 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 185.220.100.254 for 52.811363550802646 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)                                                                                                                                                                   
ytview_3  | [INFO] [11:48:23 PM] View 1 - fulfilled
ytview_3  | [INFO] [11:48:23 PM] Success - 1     Failed - 0      Total - 1
ytview_3  | [INFO] [11:48:23 PM] View 2 - fulfilled
ytview_3  | [INFO] [11:48:23 PM] Success - 2     Failed - 0      Total - 2
ytview_3  | [INFO] [11:48:23 PM] View 3 - fulfilled
ytview_3  | [INFO] [11:48:23 PM] Success - 3     Failed - 0      Total - 3
ytview_3  | [INFO] [11:48:23 PM] View 4 - fulfilled
ytview_3  | [INFO] [11:48:23 PM] Success - 4     Failed - 0      Total - 4
ytview_3  | [INFO] [11:48:23 PM] View 5 - fulfilled
ytview_3  | [INFO] [11:48:23 PM] Success - 5     Failed - 0      Total - 5
ytview_3  | [INFO] [11:48:23 PM] View 6 - fulfilled
ytview_3  | [INFO] [11:48:23 PM] Success - 6     Failed - 0      Total - 6
ytview_3  | [INFO] [11:48:23 PM] Starting TOR.
ytview_3  | [SUCCESS] [11:48:23 PM] Started TOR successfully
ytview_5  | [SUCCESS] [11:48:24 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 46.165.245.154 for 51.27143703589482 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)                                                                                                                                                                     
ytview_5  | [INFO] [11:48:24 PM] View 7 - fulfilled
ytview_5  | [INFO] [11:48:24 PM] Success - 7     Failed - 0      Total - 7
ytview_5  | [INFO] [11:48:24 PM] View 8 - fulfilled
ytview_5  | [INFO] [11:48:24 PM] Success - 8     Failed - 0      Total - 8
ytview_5  | [INFO] [11:48:24 PM] View 9 - fulfilled
ytview_5  | [INFO] [11:48:24 PM] Success - 9     Failed - 0      Total - 9
ytview_5  | [INFO] [11:48:24 PM] View 10 - fulfilled
ytview_5  | [INFO] [11:48:24 PM] Success - 10    Failed - 0      Total - 10
ytview_5  | [INFO] [11:48:24 PM] View 11 - fulfilled
ytview_5  | [INFO] [11:48:24 PM] Success - 11    Failed - 0      Total - 11
ytview_5  | [INFO] [11:48:24 PM] View 12 - fulfilled
ytview_5  | [INFO] [11:48:24 PM] Success - 12    Failed - 0      Total - 12
ytview_5  | [INFO] [11:48:24 PM] Starting TOR.
ytview_5  | [SUCCESS] [11:48:24 PM] Started TOR successfully
ytview_2  | [SUCCESS] [11:48:27 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 179.43.167.230 for 57.15203642770241 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)
ytview_2  | [SUCCESS] [11:48:28 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 192.42.116.16 for 57.02661892709723 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)
ytview_2  | [INFO] [11:48:28 PM] View 7 - fulfilled
ytview_2  | [INFO] [11:48:28 PM] Success - 7     Failed - 0      Total - 7
ytview_2  | [INFO] [11:48:28 PM] View 8 - fulfilled
ytview_2  | [INFO] [11:48:28 PM] Success - 8     Failed - 0      Total - 8
ytview_2  | [INFO] [11:48:28 PM] View 9 - fulfilled
ytview_2  | [INFO] [11:48:28 PM] Success - 9     Failed - 0      Total - 9
ytview_2  | [INFO] [11:48:28 PM] View 10 - fulfilled
ytview_2  | [INFO] [11:48:28 PM] Success - 10    Failed - 0      Total - 10
ytview_2  | [INFO] [11:48:28 PM] View 11 - fulfilled
ytview_2  | [INFO] [11:48:28 PM] Success - 11    Failed - 0      Total - 11
ytview_2  | [INFO] [11:48:28 PM] View 12 - fulfilled
ytview_2  | [INFO] [11:48:28 PM] Success - 12    Failed - 0      Total - 12
ytview_2  | [INFO] [11:48:28 PM] Starting TOR.
ytview_2  | [SUCCESS] [11:48:28 PM] Started TOR successfully
ytview_4  | [SUCCESS] [11:48:31 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 195.176.3.23 for 45.47183420704917 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)
ytview_1  | [SUCCESS] [11:48:36 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 45.9.148.217 for 51.800268099981956 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)
ytview_1  | [SUCCESS] [11:48:38 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 87.118.92.43 for 58.13667194533737 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)
ytview_4  | [SUCCESS] [11:48:40 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 109.70.100.35 for 55.814975266193755 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)
ytview_1  | [SUCCESS] [11:48:42 PM] Attempted https://www.youtube.com/watch?v=dQw4w9WgXcQ with IP: 77.247.181.162 for 56.57729011613876 seconds. (Init View Count: 356 Current View Count: 356 Views added this session: 0)
ytview_1  | [INFO] [11:48:42 PM] View 7 - fulfilled
ytview_1  | [INFO] [11:48:42 PM] Success - 7     Failed - 0      Total - 7
ytview_1  | [INFO] [11:48:42 PM] View 8 - fulfilled
ytview_1  | [INFO] [11:48:42 PM] Success - 8     Failed - 0      Total - 8
ytview_1  | [INFO] [11:48:42 PM] View 9 - fulfilled
ytview_1  | [INFO] [11:48:42 PM] Success - 9     Failed - 0      Total - 9
ytview_1  | [INFO] [11:48:42 PM] View 10 - fulfilled
ytview_1  | [INFO] [11:48:42 PM] Success - 10    Failed - 0      Total - 10
ytview_1  | [INFO] [11:48:42 PM] View 11 - fulfilled
ytview_1  | [INFO] [11:48:42 PM] Success - 11    Failed - 0      Total - 11
ytview_1  | [INFO] [11:48:42 PM] View 12 - fulfilled
ytview_1  | [INFO] [11:48:42 PM] Success - 12    Failed - 0      Total - 12
ytview_1  | [INFO] [11:48:42 PM] Starting TOR.
ytview_1  | [SUCCESS] [11:48:42 PM] Started TOR successfully

**Comment by soumyadityac** [comment]
In rare instances, because of the huge amount of lag associated with TOR, pipelining, etc. the proxy tunnel might timeout. In such cases, the view action is cancelled and the bot proceeds with the next batch with a fresh set of IPs. 

Will need to improve logging and categorise these messages as WARNINGS instead of ERRORS.
