### ISSUE TITLE
Tor being blocked

### ISSUE THREAD

**Issue by AlyNeumann** [soumyadityac/youtube-viewer#13]
Hi! Thank you for this super educational project! I can't seem to get past this issue though, youtube seems to be blocking TOR. Has anyone seen this before? I just get the message from the logFailedAttempt function on the logger.js file. Thank you!

**Comment by calvinti12** [comment]
Yes I’m having the same issue any help

**Comment by soumyadityac** [comment]
Please refer to [this](https://github.com/soumyadityac/youtube-viewer/issues/8)
