### ISSUE TITLE
so:libre2.so.0 (missing)

### ISSUE THREAD

**Issue by und3f1ned** [soumyadityac/youtube-viewer#16]
`ERROR: unsatisfiable constraints:
  so:libre2.so.0 (missing):
    required by: chromium-85.0.4183.121-r0[so:libre2.so.0]`

After `docker-compose build`

**Comment by maksimay** [comment]
@und3f1ned how did you solve it? Having the same issue, what was your fix?

**Comment by und3f1ned** [comment]
@maksimay 
Change first string in Dockerfile to
`FROM alpine:3.12`

**Comment by maksimay** [comment]
Thx already fixed it :-)
