### ISSUE TITLE
I want to close the chromium browser and start new one. But this code is making a new chromium instance without closing the previous one even its work has been completed.

### ISSUE THREAD

**Issue by shakti-kc** [soumyadityac/youtube-viewer#45]

**Comment by fdciabdul** [comment]
you can add await browser.close();

in this line 

https://github.com/soumyadityac/youtube-viewer/blob/9397b3f00e058a591cc1df6c8d1f5c85539c1209/services/youtubeBrowser.service.js#LL38C3-L38C24
