### ISSUE TITLE
I want to know if the bot is running or not

### ISSUE THREAD

**Issue by nssatish6982** [soumyadityac/youtube-viewer#9]

**Comment by nssatish6982** [comment]
I have followed the steps mentioned in your page
i ran the docker compose command

How can i confirm if it is running successfully

**Comment by soumyadityac** [comment]
Running the application would ofcourse lead to a stream of logs in your console with errors, warnings or success messages, unless you start the containers in detached mode 

[https://docs.docker.com/compose/faq/#whats-the-difference-between-up-run-and-start](url)
